[project]
name = "craft-text-detector"
version = "0.4.3"
description = "Packaged PyTorch-based implementation of the CRAFT text detector."
readme = "README.md"
requires-python = ">=3.9,<3.10"
authors = [
    { name = "Fatih Cagatay Akyon" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
keywords = [
    "machine-learning",
    "deep-learning",
    "ml",
    "pytorch",
    "text",
    "text-detection",
    "craft"
]
license = "MIT"
dependencies = [
    "basenet>=0.1.0",
    "gdown>=5.2.0",
    #"keras<3.0.0",
    "numpy<2.0.0",
    "onnx>=1.18.0",
    #"onnx-tf>=1.10.0",
    # "tensorflow==2.18.0",
    # "tensorflow-addons>=0.23.0",
    # "tensorflow-probability>=0.25.0",,
    "opencv-python-headless>=4.11.0.86",
    "torch>=1.12.0",
    "torchvision==0.13.0",
]

[tool.uv]
environments = [
    "sys_platform == 'linux'",
]
#-environments = "manylinux2014_aarch64"

# [tool.uv.sources]
# torch = [
#   { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
#   { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
# ]
# torchvision = [
#   { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
#   { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
# ]

# [[tool.uv.index]]
# name = "pytorch-cpu"
# url = "https://download.pytorch.org/whl/cpu"
# explicit = true

# [[tool.uv.index]]
# name = "pytorch-cu128"
# url = "https://download.pytorch.org/whl/cu128"
# explicit = true

[tool.bumpversion]
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        \\.                                             # period separator for pre-release section
        (?P<pre_l>[a-zA-Z-]+)                           # pre-release label
        (?P<pre_n>0|[1-9]\\d*)                          # pre-release version number, for adding a branch name, add this to the next line: (?:\\+\\w+)
    )?                                                  # pre-release section is optional
"""
serialize = [
    "{major}.{minor}.{patch}.{pre_l}{pre_n}", #+{short_branch_name}",
    "{major}.{minor}.{patch}",
]
search = "{current_version}"
replace = "{new_version}"
regex = true
ignore_missing_version = false
ignore_missing_files = false
tag = true
tag_name = "v{new_version}"
moveable_tags = [
    "latest",
]
allow_dirty = false
commit = true
sign_tags = false
tag_message = "Bump version: {current_version} → {new_version}"
message = "Bump version: {current_version} → {new_version}"
commit_args = "--no-verify"
pre_commit_hooks = ["uv sync", "git add uv.lock"]

[[tool.bumpversion.files]]
filename = "craft_text_detector/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[tool.bumpversion.parts.pre_l]
values = ["dev", "post"]
optional_value = "post"

[tool.hatch.version]
path = "craft_text_detector/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["craft_text_detector/"]
